### ISSUE TITLE
Always reset blind position to 50% ?

### ISSUE THREAD

**Issue by exzz** [dubocr/homebridge-tahoma#144]
Hi Romain,

First of all, many thanks for your wonderfull work, it really improves my everyday homekit experience.

I would like to understand why my (stateless) RTS blinds does not always reset to 50% position even with "defaultPosition" value force to this value.

My use case is the following one:
1/ I (re)start homebridge
2/ My blind position is reported as "50%" as expected
3/ I close a blind through homekit app
4/ My blind position is stuck to "closed" position
5/ If I change blind position with RTS remote or tohama app, I cannot close it anymore with homekit as it still reported as "closed"

Is there a way to force blind position report back to 50%, whatever homekit latest command ?

Here is my config:

```yaml
{
           "platform": "Tahoma",
            "name": "Tahoma",
            "user": "XXX",
            "password": "XXX",
            "refreshPeriod": 60,
            "exposeScenarios": true,
            "exclude": "Alarm",
            "WindowCovering": {
                "defaultPosition": 50
            }
}
```
